% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Exploring Transmission Expansion in an RE future in India},
  pdfauthor={Shubhangi Gupta, Aditi Jackson, David Robinson},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Exploring Transmission Expansion in an RE future in India}
\author{Shubhangi Gupta, Aditi Jackson, David Robinson}
\date{2024-03-29}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

\hypertarget{motivation-relevance-objectives}{%
\subsection{Motivation, Relevance,
Objectives}\label{motivation-relevance-objectives}}

As one of the world's fastest growing emerging economies, India's demand
for electricity is increasing every year - fueled by newly electrified
homes, growing industry, urbanization, rising income levels, a higher
demand for cooling and in a low carbon future - the electrification of
end use sectors like industry and transport. To address this demand, the
country plans to almost double its power capacity to 900 GW by 2030, up
from 427 GW today.
\href{https://energy.economictimes.indiatimes.com/news/power/indias-power-demand-projected-to-reach-366-gw-by-2030-capacity-expansion-to-900-gw-targeted/106971394}{Source}.
At the same time, as a signatory of the Paris Agreement, India has
committed to reducing its national emissions to net zero by 2070, with
an intermediate target of transitioning 50\% of its electric generation
capacity to clean sources by 2030 as part of its NDC to the UNFCCC.
\href{https://unfccc.int/sites/default/files/NDC/2022-08/India\%20Updated\%20First\%20Nationally\%20Determined\%20Contrib.pdf}{Source}.
In line with this growing demand for electricity and simultaneous need
to decarbonize, India has announced a complementary target of achieving
500 GW of renewable energy capacity by 2030.
\href{https://www.reuters.com/article/idUSKCN1TQ1QW/}{Source}. However,
to ensure that this new clean energy translates into emissions
reductions, integrating such high levels of variable renewable energy
(VRE) into the electric system requires a concurrent expansion and
modernisation of the grid, so that issues around connecting new RE
capacity to load centres, power flow management and congestion, and
managing higher load volumes do not impede the clean energy transition.

With this context in mind, in this study, we aim to: Explore how India's
transmission capacity has changed over the last several years and thus
forecast it based on historical trends. This would allow us to identify
what capacity it will reach in 2030 in a ``business as usual'' scenario.
We then compare our finding to what is needed by 2030 to integrate the
additional 500 GW of RE into the grid as assessed in the literature, to
highlight thr gap between current trends and what is needed.

\hypertarget{dataset-information-and-methods}{%
\subsection{Dataset information and
methods}\label{dataset-information-and-methods}}

For this study, we used data on the line length (in ckm) of transmission
lines installed in India, taken from the ``India Climate and Energy
Dashboard (ICED)'' developed by the Government of India's inhouse think
tank - the NITI Aayog. The data is monthly and extends from April 2015
to January 2024 and represents the length of new transmission lines (in
'00 kms) added across the country in each month during this timeframe.
While line length does not reflect voltage levels and different types of
transmission and distribution, the portal from which we acquired the
data clearly states that this length refers to transmission only. We
also explored the additions to transmission capacity by voltage to
determine if the declining trend could be attributed to the addition of
higher efficiency voltage lines but found, based on research from Indian
think-tank Prayas, that this is not the case - rendering line length a
simple yet effective metric to explore how thr transmission grid has
expanded in India over the last decade.
\href{https://indiatransmission.org/transmission-line}{Source}. However,
forecasting annual additions was misleading as it had a negative
declining trend overtime while we were forecasting transmission growth
in India. Upon reflection, we decided to transform annual additions to
cumulative line length in each time period instead which allowed us to
represent how total transmission capacity has grown over time more
accurately. Plotting cumulative line capacity over time showed a clear
increasing trend.

The original dataset included two columns of interest - additional line
length (ckm) in each month, and month/year of completion. In order to
create a time series dataset of total line length in each month, we
wrangled it using the following process:

Stage 1: Wrangling and methods \n (1) Importing the dataset, subsetting
it to only retain these two columns of interest, and renaming them to
simpler names. Packages used were tidyverse, dplyr, lubridate, readxl,
ggplot2, forecast, Kendall, tseries, smooth, readr, zoo, cowplot,
kableExtra \n (2) Checking if there were any NAs (there weren't). \n (3)
Splitting the ``month/ year of completion column'' that was a string
into the month and year separately, converting the year from two digits
to four digits (ex: ``15'' to ``2015''), pasting that back with the
month column separated by a ``-'' and then using lubridate to convert it
into a date object. \n (4) Using the group\_by(Date) function to add up
all the capacity additions in the same month - that in the original
dataset were broken up across multiple rows based on the regions of
India that they occurred in (we only consider total nation-wide capacity
and do not look at this data's breakup across states/ regions). \n (5)
Using the cumsum() function to sum the line length of the previous
month's total capacity (calculated) to the current month's capacity
addition \n (original data). This gave us a dataset with two columns:
Date and total transmission line length (ckm) until that month. \n (6)
Plotting these two columns along with an lm line to check the trend. \n
This concluded the first stage of wrangling the data to acquire our
final dataset to be used for the analysis.

Stage 2: Initial Exploration \n (1) Converting the data into a time
series object.\n (2) Plotting the ACF and PACF.\n (3) Decomposing the
time series object (multiplicative)\n (4) Running an SMK and ADF test.\n

Stage 3: Fitting the model and forecasting to training data \n (1)
Breaking up the dataset into training and testing: \n (i) Training:
April 2015 to March 2023 \n (ii) Testing: April 2023 - January 2024 \n
(these follow India's financial year cycle of April-March) \n (2)
Fitting the models: \n (i) For ARIMA, identifying the best ARIMA model
using auto.arima. Besides that, we fit the TBATS and Neural Network.\n
(ii) Fitting the models mentioned in the previous step to the training
data, and using the summary() and checkresiduals() functions to check
the result. \n (3) Forecasting the fitted model to the next one year
(testing data) using the forecast function.\n (4) Plotting the result
along with the original data using autoplot and autolayer, as well as
using the accuracy() function to explore the goodness of fit and
forecast of the model to the data.\n

\hypertarget{data-structure}{%
\subsection{Data Structure}\label{data-structure}}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5000}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 2\tabcolsep) * \real{0.5000}}@{}}
\caption{Data Structure Summary - NITI Aayog}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Detail
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Description
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Detail
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Description
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Data Source & India Climate and Energy Dashboard \\
Retrieved from &
\url{https://iced.niti.gov.in/energy/electricity/transmission/transmission-lines} \\
Variables Used & Transmission Line Length \\
Units Used & ckm ('00 km) \\
Data Range & April 2015 - January 2024 \\
Minimum Value & 737 ckm (April 2015) \\
Maximum Value & 167889 ckm (January 2024) \\
\end{longtable}

\hypertarget{data-wrangling-initial-plot}{%
\subsection{Data Wrangling \& initial
plot}\label{data-wrangling-initial-plot}}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/wrangle-1.pdf}

\hypertarget{analysis}{%
\section{Analysis}\label{analysis}}

\hypertarget{plots}{%
\subsection{Plots}\label{plots}}

Initial analysis included creating a time series of Total Line Length
(ckm), plotting the series, and generating its ACF and PACF. The time
series plot shows a strong, positive trend. The ACF plot decays
exponentially, and the PACF plot is only significant at the first lag.
Taken together, the ACF and PACF plots suggest that the series follows
an autoregressive process.

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/time series-1.pdf}

\hypertarget{decomposition}{%
\subsection{Decomposition}\label{decomposition}}

The series was then decomposed into observed, trend, seasonality, and
residuals. The observed and trend components both increase similarly
over time. However, the seasonal component is not representative of the
dataset. Upon further inspection, we observed that the seasonality was
too uniform in magnitude and may not be part of the dataset. While there
may be some seasonality due to construction start and end dates for
transmission projects (e.g.~before and after Monsoon Season), it is more
likely that the decompose function in R is forcing a seasonal component
that does not exist within the data. As such, we did not de-season the
data and instead chose to fit models that could handle seasonality (see
below). The residuals looked fairly random, so we did not see the need
for further manipulation before fitting models.

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/decompose-1.pdf}

\begin{verbatim}
## NULL
\end{verbatim}

\hypertarget{statistical-tests}{%
\subsection{Statistical Tests}\label{statistical-tests}}

To determine whether or not the series was stationary (i.e.~if its
statistical properties like mean and variance do not change over time),
we employed the Seasonal Mann-Kendall (SMK) and Augmented Dickey-Fuller
(ADF) tests. The SMK test produced a positive test statistic (Tau = 1)
and a significant p-value (2-sided p-value =\textless{} 2.22e-16) at the
95\% confidence level. This indicates non-stationarity and a positive
deterministic trend. The ADF test produced a negative test statistic
(Dickey-Fuller = -3.2942) and an insignificant p-value (p = 0.07586) at
a 95\% confidence level. Thus we do not have enough evidence to reject
the null hypothesis that the series has a unit root
(i.e.~non-stationarity). Instead, we would lean towards accepting the
alternative hypothesis that the time series in question is stationary
(i.e.~does not possess a unit root).

\begin{verbatim}
## Score =  416 , Var(Score) = 1050.667
## denominator =  416
## tau = 1, 2-sided pvalue =< 2.22e-16
## NULL
\end{verbatim}

\begin{verbatim}
## 
##  Augmented Dickey-Fuller Test
## 
## data:  transmission_ts
## Dickey-Fuller = -3.2942, Lag order = 4, p-value = 0.07586
## alternative hypothesis: stationary
\end{verbatim}

\hypertarget{model-fitting-forecasting}{%
\subsection{Model Fitting \&
Forecasting}\label{model-fitting-forecasting}}

We fit three models to our transmission time series data: Seasonal ARIMA
(SARIMA), TBATS, and Neural Network.

\hypertarget{sarima---model-and-forecast}{%
\subsubsection{SARIMA - Model and
Forecast}\label{sarima---model-and-forecast}}

We chose to start with the SARIMA model given its relative simplicity
and ability to handle seasonality. To fit the SARIMA model, we used the
auto.arima() function to generate the order of parameters. The function
produced the following: p = 0, d = 2, q= 1, P = 1, D = 0, Q = 1. The
non-seasonal parameters suggest no autoregressive component (p=0), 2
degrees of differencing (d=2), and a moving average component (q=1). The
seasonal part of the model suggests that there is some seasonal
autoregression (P=1), no differencing, and some seasonal moving average
(Q=1). After fitting the SARIMA model, we used the forecast function to
create a 10-month forecast and compared the values with those in our
testing data. The model appears to fit well based on visual inspection.
An accuracy table is provided below as well as a discussion of the
results. We then created a 7-year forecast (from February 2024 to March
2030) to ascertain a value for transmission build-out by 2030.

\begin{verbatim}
## Series: transmission_ts_training 
## ARIMA(0,2,1)(1,0,1)[12] 
## 
## Coefficients:
##           ma1    sar1     sma1
##       -0.9451  0.8338  -0.5295
## s.e.   0.0320  0.1292   0.2064
## 
## sigma^2 = 1090869:  log likelihood = -788.27
## AIC=1584.53   AICc=1584.98   BIC=1594.7
\end{verbatim}

\begin{verbatim}
## Series: transmission_ts_training 
## ARIMA(0,2,1)(1,0,1)[12] 
## 
## Coefficients:
##           ma1    sar1     sma1
##       -0.9451  0.8338  -0.5295
## s.e.   0.0320  0.1292   0.2064
## 
## sigma^2 = 1090869:  log likelihood = -788.27
## AIC=1584.53   AICc=1584.98   BIC=1594.7
## 
## Training set error measures:
##                     ME     RMSE      MAE         MPE     MAPE       MASE
## Training set -88.36536 1016.884 760.9757 -0.09538527 1.445726 0.03940281
##                     ACF1
## Training set -0.01866278
\end{verbatim}

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/SARIMA model and forecast-1.pdf}

\begin{verbatim}
## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(0,2,1)(1,0,1)[12]
## Q* = 9.0798, df = 16, p-value = 0.9101
## 
## Model df: 3.   Total lags used: 19
\end{verbatim}

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/SARIMA model and forecast-2.pdf}

\begin{verbatim}
##                     ME     RMSE      MAE         MPE     MAPE       MASE
## Training set -88.36536 1016.884 760.9757 -0.09538527 1.445726 0.03940281
##                     ACF1
## Training set -0.01866278
\end{verbatim}

\hypertarget{tbats---model-and-forecast}{%
\subsubsection{TBATS - Model and
Forecast}\label{tbats---model-and-forecast}}

TBATS was the next model we fit to our time series. Given the
uncertainty around seasonality in our data, we opted for TBATS since the
model can handle seasonal variation. We fit the model using the tbats()
function from the forecast package. We then used the TBATS model to
generate a forecast and compared the forecast to our original data.
Again, we forecasted 7 years of values in order to obtain a value for
transmission build-out by 2030. Upon inspection, the forecast compares
favorably with the test values from our original data.

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/TBATS-1.pdf}

\begin{verbatim}
##                   ME     RMSE     MAE        MPE     MAPE       MASE
## Training set 13.7543 887.3142 685.352 -0.6353815 2.303935 0.03548707
##                     ACF1
## Training set -0.00187256
\end{verbatim}

\hypertarget{neural-network---model-and-forecast}{%
\subsubsection{Neural Network - Model and
Forecast}\label{neural-network---model-and-forecast}}

The last model we fit was a neural network since they are able to
capture complex patterns in time series data. We used the function
nnetar() from package `forecast' with p = 1 and P = 1 (taken from the
parameters of our SARIMA model). Similar to our workflow with SARIMA and
TBATS, we created a forecast with the Neural Network model and compared
the values to our original data. Then, we created a 7-year forecast to
obtain a value for transmission build-out by 2030. Upon inspection, the
forecast compares favorably with the test values from our original data.

\includegraphics{GuptaJacksonRobinson_ENV797_TSA_FinalProject_files/figure-latex/neural network-1.pdf}

\begin{verbatim}
##                    ME     RMSE      MAE        MPE     MAPE      MASE      ACF1
## Training set 4.434108 2516.243 1984.251 -0.1918467 2.216477 0.1027432 0.8875918
\end{verbatim}

\hypertarget{checking-accuracy}{%
\subsection{Checking Accuracy}\label{checking-accuracy}}

Across the three models and forecasts that were run, we evaluated the
accuracy of each model to understand the best fit. By Root Mean Squared
Error or RMSE equal to 887, the best model is TBATS. By Mean Absolute
Percentage Error or MAPE equal to 1.44, the best model is SARIMA.
Additionally, we added a table to show various accuracy metrics in
detail across SARIMA, TBATS, and NN models for detailed, quantitative
comparison across a variety of accuracy measures.

\begin{verbatim}
## The best model by RMSE is: TBATS
\end{verbatim}

\begin{verbatim}
## The best model by MAPE is: SARIMA
\end{verbatim}

\hypertarget{summary-and-conclusions}{%
\section{Summary and Conclusions}\label{summary-and-conclusions}}

Our primary research question was ``How does this compare to the
transmission capacity needed in a net zero-aligned renewable-heavy
future?''

In seeking a reference point from the literature by which to measure the
success of our model, we found that in order to achieve India's goal of
integrating 500 GW of renewable energy by 2030, an additional 50,890 Ckm
of transmission line length would need to be built
\href{https://cea.nic.in/wp-content/uploads/notification/2022/12/CEA_Tx_Plan_for_500GW_Non_fossil_capacity_by_2030.pdf\#:~:text=India\%20has\%20envisaged\%20to\%20increase\%20the\%20non\%2Dfossil,energy\%20potential\%2C\%20needs\%20to\%20be\%20connected\%20to}{Source}
over the 2022-23 capacity of 487,367 Ckm.
\href{https://web.cvent.com/event/681be785-fd13-4645-8c92-3305ca1454c5/summary}{Source}.
Adding these estimates of needed transmission line build-out and current
transmission line length, the literature suggests that cumulative
transmission line capacity would need to reach 529,257 Ckm by 2030 to
achieve its 2030 RE target.

\begin{verbatim}
##           Jan      Feb      Mar      Apr      May      Jun      Jul      Aug
## 2023                            158662.4 159416.7 160716.2 162063.3 163202.7
## 2024 168047.5 169927.2 171919.3 172707.5 173492.3 174731.8 176010.8 177116.7
## 2025 181935.7 183658.9 185475.7 186288.8 187099.1 188288.4 189510.7 190588.7
## 2026 195386.2 196978.8 198649.6 199483.5 200314.9 201462.4 202637.5 203692.2
## 2027 208471.8 209955.5 211504.5 212355.7 213204.8 214317.5 215453.1 216488.4
## 2028 221253.0 222646.1 224093.4 224959.0 225822.9 226906.6 228009.3 229028.4
## 2029 233780.6 235098.0 236460.6 237338.3 238214.5 239273.9 240349.3 241354.9
## 2030 246096.6 247350.9 248643.0                                             
##           Sep      Oct      Nov      Dec
## 2023 164500.6 165430.6 166229.2 167067.2
## 2024 178354.8 179286.1 180107.8 180962.5
## 2025 191776.9 192709.3 193550.4 194418.9
## 2026 204838.8 205772.1 206629.3 207509.3
## 2027 217600.3 218534.4 219405.0 220294.6
## 2028 230111.4 231046.1 231927.9 232825.6
## 2029 242413.7 243349.0 244240.1 245144.4
## 2030
\end{verbatim}

\begin{verbatim}
##           Jan      Feb      Mar      Apr      May      Jun      Jul      Aug
## 2023                            157945.4 158123.5 159441.2 160024.0 161347.2
## 2024 165922.1 167429.7 169427.4 169373.7 169447.2 170661.3 171141.5 172363.1
## 2025 176443.2 177854.6 179756.9 179608.7 179588.7 180710.0 181098.3 182228.8
## 2026 185865.9 187191.0 189008.0 188775.2 188671.3 189709.5 190015.4 191064.4
## 2027 194304.7 195552.7 197293.1 196984.5 196805.5 197769.4 198001.6 198977.5
## 2028 201862.4 203041.3 204713.2 204336.8 204090.5 204987.7 205153.9 206064.4
## 2029 208631.1 209748.0 211358.6 210921.4 210614.9 211452.4 211559.5 212411.3
## 2030 214693.0 215754.5 217310.2                                             
##           Sep      Oct      Nov      Dec
## 2023 163473.3 164021.0 164440.9 165486.3
## 2024 174388.4 174836.2 175157.2 176104.5
## 2025 184163.8 184522.2 184754.6 185614.2
## 2026 192918.6 193196.9 193350.0 194130.9
## 2027 200759.3 200965.9 201047.9 201758.4
## 2028 207781.4 207923.8 207942.1 208589.5
## 2029 214070.3 214155.1 214116.4 214707.4
## 2030
\end{verbatim}

From our SARIMA forecast, the projected value for January of 2030 is
246,863 Ckm in March 2030 and from the TBATS model, it is 217,310.2.
This highlights that if transmission lines length added until 2030
follow historical/ BAU trends, they would only achieve half of the
required 529,257 Ckm - which would significantly impede RE expansion in
India. Our findings thus hihglight the need for concerted policy and
industry effort to enhance transmission build out to keep pace with the
growth of RE in India.

\end{document}
